apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev
namespace: dev

resources:
- ../../bases
- namespace.yaml

configMapGenerator:
- name: nginx-page-cm
  files:
  - page=nginx/pages/index.html
- name: nginx-server-cm
  files:
  - server=nginx/servers/server.conf

secretGenerator:
- name: nginx-user-secret
  files:
  - user=secrets/user.txt

helmChartInflationGenerator:
- chartName: nginx
  chartRepoUrl: https://charts.bitnami.com/bitnami
  chartVersion: 15.4.2
  releaseName: nginx
  values: values.yaml