apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: nginx-page-cm
  files:
  - page=nginx/pages/index.html

helmChartInflationGenerator:
- chartName: nginx
  chartRepoUrl: https://charts.bitnami.com/bitnami
  chartVersion: 15.4.2
  releaseName: nginx
  values: values.yaml