apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: backend-pod
  template:
    metadata:
      name: backend-pod
      labels:
        name: backend-pod
    spec:
      containers:
      - name: backend-container
        image: k8s-backend-go
        imagePullPolicy: IfNotPresent