apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    name: backend-pod
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080