apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#helmChartInflationGenerator:
#- chartName: ingress-nginx
#  chartRepoUrl: https://kubernetes.github.io/ingress-nginx
#  chartVersion: 4.1.4
#  releaseName: ingress-nginx
#  values: values.yaml

helmChartInflationGenerator:
- chartName: nginx
  chartRepoUrl: https://charts.bitnami.com/bitnami
  chartVersion: 15.4.2
  releaseName: nginx
  values: values.yaml